cache: &cache-template
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  paths:
    - target/

stages:
  - rustup
  - test
  - test-ignored

rustup:
  stage: rustup
  tags:
    - rust
  script:
    - rustup update
  cache:
    <<: *cache-template
    files: []

test-nightly:
  tags:
    - rust
    - rust-nightly
  stage: test
  script:
    - rustup override add nightly
    - cargo test

test-beta:
  tags:
    - rust
    - rust-beta
  stage: test
  script:
    - rustup override add beta
    - cargo test

.test-stable:
  tags:
    - rust
    - rust-stable
  stage: test
  script:
    - rustup override add stable
    - cargo test

test-nightly-run-ignored:
  tags:
    - rust
    - rust-nightly
  stage: test-ignored
  only:
    - tags
  script:
    - rustup override add nightly
    - cargo test -- --ignored

test-beta-run-ignored:
  tags:
    - rust
    - rust-beta
  stage: test-ignored
  only:
    - tags
  script:
    - rustup override add beta
    - cargo test -- --ignored

.test-stable-run-ignored:
  tags:
    - rust
    - rust-stable
  stage: test-ignored
  only:
    - tags
  script:
    - rustup override add stable
    - cargo test -- --ignored
