[package]
name = "ded"
version = "0.2.0"
authors = ["smaximov <s.b.maximov@gmail.com>"]
description = "Directory EDit"

[dependencies]
clap = "^2.2.5"
eventual = "^0.1.6"
rust-crypto = "^0.2.35"
sequence_trie = "^0.0.13"
